### ISSUE TITLE
Import Marten.AspNetCore into the official repository

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1466]
With @jokokko 's sign off, let's import the [Marten.AspNetCore](https://github.com/jokokko/marten.aspnetcore) library into the official mothership repository and add documentation for that here.

## Tasks

- [ ] Import the code
- [ ] Add documentation
- [ ] Target `IHostBuilder` in .Net Core 3.* apps
- [ ] Target `IWebHostBuilder` in all targets (PITA to switch between the two things, but what can you do?)
- [ ] Optionally start the Async Daemon as an `IHostedService` (might break this out to a separate issue)
- [ ] Register container resolved `IDocumentSessionListener` objects that would be added to newly created `IDocumentSession` objects at resolution time (might break this out later)
- [ ] Might need to allow users to register an all custom factory for `IDocumentSession` building

**Comment by jeremydmiller** [comment]
I think now we'll just stick the extension methods on `ServiceCollection` into the main Marten lib

**Comment by jeremydmiller** [comment]
This was done through other pull requests to v3.12
