### ISSUE TITLE
Extract Generic Database Helpers to its own Library

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1467]
The core of the code that we use to do database migrations and delta detection doesn't change very often, and the tests for that code are *slow*. Let's pull all that code into a new helper library (I'm nominating a new library or two in the Baseline repository).

When we do this, let's try to make as much as the coupling as possible to `DbConnection` instead of `NpgsqlConnection` as a preparation to taking Marten cross database in a possible v5 release

## What should be pulled out

* `CommandBuilder` -- Jasper has its own copy of all this code
* ADO.Net extension methods that could easily be useful outside of Marten
* `ISchemaObject` and most of its implementations
* Code like `FunctionDelta` and `TableDelta` that do database structure difference detection
* `DdlRules` -- I'm betting that almost nobody but the original shop that wrote Marten cares about this, but still

**Comment by jeremydmiller** [comment]
## Tasks to finish

- [ ] GH action to build and publish Weasel.Postgresql
- [ ] Move ISchemaObject and some of the extension methods to the main Weasel library
- [ ] Try out all the patch command options in the CLI. Make sure there's at least smoke test coverage
- [ ] Hunt down `[Obsolete]`
- [ ] `IDbObjects` needs to be async all the way down
- [ ] `IDocumentSchema` needs to be async all the way down
- [ ]

**Comment by mysticmind** [comment]
> GH action to build and publish Weasel.Postgresql

@jeremydmiller I will take a crack at this once we are ready to publish a package to NuGet.
