### ISSUE TITLE
V4 "Self-Aggregating" Aggregate

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1664]
Right now we're just focused on using improved mechanics. For the self-aggregating projection option, 

## Support immutable aggregates

Actually pretty easy. Just support this pattern (which the codegen already does):

```
public class QuestParty
{
    public QuestParty Apply(MonsterSlayed e)
    {
         // do stuff and return a different QuestParty object
     }
}
```

Will need a test and docs to prove it though

## Enable the usage of constructor functions 

```
public class QuestParty
{
  // So you can start the QuestParty by a constructor function
   public QuestParty(QuestStarted started)
}
```

## Static Create methods

Really just for asynchronous data lookup. So:

```
public class QueryParty
{
    public static Task<QueryParty> Create(MonsterSlayed slayed, IQuerySession session);
}
```

## Tasks

- [x] Support private constructors as necessary
- [x] Auto-resolve out of EventGraph
- [x] Set the document id if aggregating by stream
- [x] Static Create() methods
- [x] public constructor functions with a single event argument
- [x] immutable aggregate class structures
