### ISSUE TITLE
V4 Aggregate and Cross-Stream View Projections

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1674]
Child of #1610 to track more specific tasks

Note: I *think* that at the least, `ViewProjection` will be a sub-class of `AggregateProjection<T>`, but I wanna keep all the tasks here because they're so closely related.

## Tasks

- [x] Definitely support non-public constructors on the aggregate/view types
- [x] Support constructors on the aggregate types that take in a known event type????
- [x] Be able to select the right constructor
- [x] Test aggregation per stream when the stream identity is a string
- [x] Validate that the aggregate id type matches the stream identity strategy type
- [x] Validate that each aggregation method has an Event argument
- [x] Validate that every method on a Projection class matches the valid conventions
- [x] Validate that if you're multi-tenanted *and* doing a projection by stream, the projected view has to be multi-tenanted as well
