### ISSUE TITLE
V5 Documentation Updates

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2034]
It's tripped up a couple folks already, and the docs aren't clear enough in how it describes the aggregate projection.

**Comment by jeremydmiller** [comment]
## Migration Guide

* Delete all generated source code because the code is a little different
* Minor change to the event store tables
* Async daemon is explicitly opt in now because of Azure Functions
* Database migration API changes
* DataTimeOffset instead of DateTime where possible




## Tasks

- [ ] Decision tree on choosing a projection type. I.e., make the distinction between AggregateProjection & ViewProjection clearer in the docs
- [ ] Multi-tenancy with database per client **big**
- [ ] New "Auto" option for pre-built code generation
- [ ] `ConfigureMarten()` in bootstrapping for post-AddMarten() configuration.
- [ ] Async daemon opt in configuration
- [ ] Async session creation for serializable transactions
- [ ] Case insensitive order by in Linq
- [ ] Secondary document store registrations. I.e., targeting multiple Marten databases in one application
- [ ] "Optimized artifact workflow" -- maybe start a new "best practices" guide
- [ ] New option to apply all pending database changes upon startup.
- [ ] `IDocumentSession.EjectAllPendingChanges()`
- [ ] `IDocumentStore.Advanced.ResetStore()` for testing support
- [ ] New testing support topic. Cover clean, reset store, overriding the host variables for the assembly & environment
- [ ] Using environment checks with Marten + Oakton
- [ ] NGram search functionality
- [ ] Linq ordering by dynamic fields

**Comment by mysticmind** [comment]
@jeremydmiller Docs for LINQ ordering by dynamic fields was already done as part of the PR. I have marked the task as done above.

**Comment by jeremydmiller** [comment]
@mysticmind I'm taking that off, thanks!

**Comment by mysticmind** [comment]
Docs for case-insensitive order by in Linq is done.

**Comment by jeremydmiller** [comment]
@mysticmind Sweet! I'm doing stuff around bootstrapping changes today -- in between distractions from dogs, spouses, and children in a packed house.

**Comment by mysticmind** [comment]
Added docs for NGram search and `IDocumentStore.Advanced.ResetAllData()`

**Comment by mysticmind** [comment]
Added docs for `Async session creation for serializable transactions`

**Comment by jeremydmiller** [comment]
## Migration Guide

* Delete all generated source code because the code is a little different
* Minor change to the event store tables
* Async daemon is explicitly opt in now because of Azure Functions
* Database migration API changes
* DataTimeOffset instead of DateTime where possible




## Tasks

- [ ] Decision tree on choosing a projection type. I.e., make the distinction between AggregateProjection & ViewProjection clearer in the docs
- [ ] Multi-tenancy with database per client **big**
- [ ] New "Auto" option for pre-built code generation
- [ ] `ConfigureMarten()` in bootstrapping for post-AddMarten() configuration.
- [ ] Async daemon opt in configuration
- [ ] Async session creation for serializable transactions
- [x] Case insensitive order by in Linq
- [ ] Secondary document store registrations. I.e., targeting multiple Marten databases in one application
- [ ] "Optimized artifact workflow" -- maybe start a new "best practices" guide
- [ ] New option to apply all pending database changes upon startup.
- [x] `IDocumentSession.EjectAllPendingChanges()`
- [ ] `IDocumentStore.Advanced.ResetStore()` for testing support
- [ ] New testing support topic. Cover clean, reset store, overriding the host variables for the assembly & environment
- [ ] Using environment checks with Marten + Oakton
- [ ] NGram search functionality
- [x] Linq ordering by dynamic fields

**Comment by jeremydmiller** [comment]
I'm declaring success today.
