### ISSUE TITLE
Integrate the new LamarCodeGeneration "auto type resolution"

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2037]
Just a hopefully better/easier way of doing the codegen ahead approach

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Document storage - dynamic
- [ ] Document storage - static
- [ ] Document storage - auto
- [ ] Event storage - dynamic
- [ ] Event storage - static
- [ ] Event storage - auto
- [ ] Compiled query - dynamic
- [ ] Compiled query - static
- [ ] Compiled query - auto
- [ ] Aggregate Projection - dynamic
- [ ] Aggregate Projection - static
- [ ] Aggregate Projection - auto
- [ ] Lightweight IMartenSession
- [ ] More validation on registering compiled query for requiring no arg compiler
- [ ] Test upfront code generation
