### ISSUE TITLE
Replace Generated Source Code Diagnostics for Events and Documents

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2054]
Got broken by yours truly, but I need to do other things first before coming back to this.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Use new approach for document storage
- [ ] Use new approach for event storage
- [ ] Use new approach for projections
- [ ] Use new approach for compiled queries
- [ ] Redo compiler warnings on public document types. See below code:


```
            try
            {
                compiler.Compile(assembly);
            }
            catch (Exception e)
            {
                if (e.Message.Contains("is inaccessible due to its protection level"))
                {
                    throw new InvalidOperationException($"Requested document type '{_mapping.DocumentType.FullNameInCode()}' must be either scoped as 'public' or the assembly holding it must use the {nameof(InternalsVisibleToAttribute)} pointing to 'Marten.Generated'", e);
                }

                throw;
            }

```
