### ISSUE TITLE
EventProjection needs to participate in the generate ahead model

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2089]
It gets completely bypassed today.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Implement `IGeneratedProjection` on `EventProjection`
- [ ] Test forward generation from `dotnet run -- codegen`
- [ ] Test within "Auto" type generation that code is written to file
- [ ] Test within "Auto" type generation that pre-built types are found for Inline projections
- [ ] Test within "Auto" type generation that pre-built types are found for async projections
