### ISSUE TITLE
Missing an `IDocumentOperations.Update<T>(T entity, Guid version)` method

### ISSUE THREAD

**Issue by alexrp** [JasperFx/marten#2439]
There is a `Store<T>(T entity, Guid version)` method for supplying the current known version of the entity, but it doesn't seem like there's an equivalent `Update()` method. This means that in some situations where it would be more semantically appropriate to use `Update()`, `Store()` has to be used instead.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] `IDocumentStorage.Update(IMartenSession session, T document, Guid? version);` -- mostly a copy of the Store() version
- [ ] New method in IDocumentOperations that calls through
- [ ] Tests of course
