### ISSUE TITLE
Blue/green & zero downtime deployment capability for single stream projections

### ISSUE THREAD

**Issue by elexisvenator** [JasperFx/marten#2846]
Currently if you want to fetch a projection (single stream projection or snapshot) and ensure that you have the latest view of that projection, then you must use either a live or an inline projection.  Live can be slow depending on the size of the stream and event store, and inline adds a lot of overhead to event writing and is harder to maintain.

Ideally it would be possible to use `session.Events.FetchForWriting<T>()` and a variant of `session.Load<T>()` and `session.LoadMany<T>` that would return an async projection but then update that projection to have all events.

The building blocks to do this already exist in marten, though there are some design considerations:
- What to call the `Load` variant to not be confused with the regular version.
- In order for this to work the projection must be a single stream projection or self aggregate and must include the event version. I'm not a big fan of enforcing this shape restriction but don't see a way around it.
  - It would be great if all projections included a dedicated `mt_version` column. Just a thought.

What do people think of this as a feature? I am happy to have a go at implementing it as I have a version that works in my codebase.

**Comment by elexisvenator** [comment]
This is the version in my codebase. It uses reflection in order to get internal marten methods and to get the projection version, but I don't think this would be necessary when implemented in marten. This code is not in production use and only exists for testing,

<details>
  <summary>Test implementation</summary>
```csharp

    /// <summary>
    /// Get a snapshot of a stream using a live, async or inline projection.
    /// This will always return the latest snapshot using all events, even for async projections.
    /// </summary>
    public static async Task<TSnapshot> GetSnapshotForWriting<TSnapshot>(
        this IDocumentSession session,
        string streamKey,
        CancellationToken token = default) where TSnapshot : class
    {
        session>()
        var snapshot = await session.GetSnapshot<TSnapshot>(streamKey, token);
        if (snapshot is null)
        {
            throw new ArgumentException($"A {typeof(TSnapshot).Name} with stream key {streamKey} does not exist", nameof(streamKey));
        }

        var version = snapshot.GetProjectionVersion();
        // creates optimistic lock
        session.Events.Append(streamKey, expectedVersion: version);
        
        return snapshot;
    }

    /// <summary>
    /// Get a snapshot of a stream using a live, async or inline projection.
    /// This will always return the latest snapshot using all events, even for async projections.
    /// </summary>
    public static async Task<TSnapshot?> GetSnapshot<TSnapshot>(
        this IQuerySession session,
        string streamKey,
        CancellationToken token = default) where TSnapshot : class
    {
        var projectionSource = session.DocumentStore.GetProjectionSources()
            .FirstOrDefault(source => source.ProjectionType == typeof(TSnapshot));

        if (projectionSource is null)
        {
            throw new ArgumentException(
                $"Snapshot {typeof(TSnapshot).Name} is not a configured projection.",
                nameof(TSnapshot));
        }

        switch (projectionSource.Lifecycle)
        {
            case ProjectionLifecycle.Inline:
                return await session.LoadAsync<TSnapshot>(streamKey, token);
            case ProjectionLifecycle.Async:
                // fall through
                break;
            case ProjectionLifecycle.Live:
                return await session.Events.AggregateStreamAsync<TSnapshot>(streamKey, token: token);
            default:
                throw new ArgumentOutOfRangeException(nameof(projectionSource.Lifecycle));
        }

        // async, we need to play catchup
        var snapshot = await session.LoadAsync<TSnapshot>(streamKey, token);
        if (snapshot is null)
        {
            // pull as a live aggregate 
            return await session.Events.AggregateStreamAsync<TSnapshot>(streamKey, token: token);
        }

        // play catchup, which should do nothing if we are on the latest version
        return await session.Events.AggregateStreamAsync(
            streamKey,
            state: snapshot,
            fromVersion: snapshot.GetProjectionVersion() + 1, 
            token: token);
    }

    /// <summary>
    /// Reflection to get the configured projection sources from marten.
    /// Not needed if implemented in marten
    /// </summary>
    private static IEnumerable<IReadOnlyProjectionData> GetProjectionSources(this IDocumentStore store)
    {
        var documentStore = (DocumentStore)store;
        return documentStore.Options.Projections
            .GetFieldValue<IList<IProjectionSource>>("<All>k__BackingField");
    }

    private const BindingFlags Bindings =
        BindingFlags.Public |
        BindingFlags.NonPublic |
        BindingFlags.Instance;

    private static TValue GetFieldValue<TValue>(this object obj, string name)
    {
        var field = obj.GetType().GetField(name, Bindings);
        return (TValue)field?.GetValue(obj)!;
    }

    /// <summary>
    /// Get the projection version from a projection object.
    /// Marten does this internally through the use of codegen.
    /// When called from marten we could use the codegen to resolve this.
    /// </summary>
    private static long GetProjectionVersion<TProjection>(this TProjection? projection)
    {
        if (projection is null)
        {
            return 0;
        }

        long GetValue(PropertyInfo property)
        {
            if (property.PropertyType == typeof(int))
            {
                return (int)property.GetValue(projection)!;
            }

            if (property.PropertyType == typeof(long))
            {
                return (long)property.GetValue(projection)!;
            }

            throw new ArgumentException(
                $"Property did not have the expected int or long datatype on projection {typeof(TProjection).Name}. Property is '{property.Name}', type is '{property.PropertyType.Name}'",
                nameof(projection));
        }

        var type = typeof(TProjection);
        var properties = type.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
        var propertyWithVersionAttribute =
            properties.FirstOrDefault(prop => prop.IsDefined(typeof(VersionAttribute), true));
        if (propertyWithVersionAttribute is not null)
        {
            return GetValue(propertyWithVersionAttribute);
        }

        var namedProperty = properties.FirstOrDefault(prop =>
            prop.Name.Equals("Version", StringComparison.OrdinalIgnoreCase) &&
            !prop.IsDefined(typeof(MartenIgnoreAttribute), true));
        if (namedProperty is not null)
        {
            return GetValue(namedProperty);
        }

        throw new ArgumentException(
            $"Could not find a version property or field on projection {typeof(TProjection).Name}. Field should either have [Version] attribute or be called 'Version' and not have [MartenIgnore] attribute",
            nameof(projection));
    }
```
</details>

**Comment by jeremydmiller** [comment]
@elexisvenator Oskar, Babu, and I have talked about that a little bit as part of a bigger "zero downtime deployment" strategy.  I've thought about this one a bit. There's already a strategy pattern underneath `FetchForWriting()` for live vs inline. What I thought we'd do for the async version is have it in one query get the latest saved version of the aggregate and the events for that aggregate **after** the last saved version. Then the fetching strategy can be smart enough to give you what's persisted if it's up to date, or selectively apply the other events on top of that. 

We'd have to make some other changes to bring the stream version over to the persisted aggregate's database table.

**Comment by elexisvenator** [comment]
Using a single query to get all relevant data would definitely help ensure query performance is maintained. Is there any benefit to supporting a `Load` for an async projection that skips this? Just wondering about it from a usability perspective as it would be possible for a load call to return a different results to a query-by-id call.

**Comment by jeremydmiller** [comment]
## Planning

As a way to allow for blue/green deployment, allow single stream projections to be registered with a revision/version number that effectively makes the table and function names and hence storage for the aggregate type be suffixed with let's say a "_2" for version 2. This will allow "blue" nodes to use one version of the aggregate, and "green" nodes to use another. 

## Tasks

- [ ] `ProjectionBase.ProjectionVersion : int`
- [ ] New `AsyncProjectionVersionPolicy` that adds the document alias suffix for the int version on single stream projections. Watch custom projection
- [ ] New `IFetchPlanner` interface
- [ ] `EventStore.determineFetchPlan()` should use `IFetchPlanner` objects registered on `StoreOptions.Projections`
- [ ] New syntax of some sort to register custom `IFetchPlanner`
- [ ] `IFetchPlanner` for inline
- [ ] `IFetchPlanner` for live
- [ ] `IFetchPlanner` for async/catch up mode!!!
- [ ] Test with custom `SingleStreamProjection`
- [ ] Test with "self-aggregate" `Snapshot` model

## IFetchPlanner

```csharp
public interface IFetchPlanner
{
    bool TryMatch<TDoc, TId>(storage, IEventIdentityStrategy<TId>, EventGraph);
}
```

**Comment by jeremydmiller** [comment]
BOOM, this works locally!
