### ISSUE TITLE
Overhaul Command Execution Pipeline

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2887]
I'm subsuming a couple older issues here about retry policies (#2265), Hot Chocolate integration (#2738), and more advanced Npgsql usage #2787.

**Comment by jeremydmiller** [comment]
## Goals

* Make the retry mechanics be more efficient. Depending on Lambda closures generates a lot of object allocations we could eliminate
* Utilize ADO.Net command batching (NpgsqlBatch) as that's more efficient than our old `CommandBuilder` mechanism from Marten 1.0
* The current retry mechanics don't actually work because they don't reset the connection
* Reevaluate the database connection lifecycle, especially the sticky connection to session mechanics from the 1.0 days
* Improve Marten's usability within Hot Chocolate, and that might mean ending the stick connection thing
* Reevaluate whether and how we allow for users to execute arbitrary SQL using a session. Easy to queue up commands now w/ the QueueSqlCommand(). See what folks actually do now.
* Reevaluate whether or not we even care about Dapper integration anymore

## Notes

**Comment by gfoidl** [comment]
> Improve throughput by moving to positional parameters in the SQL construction. Only hurdle is the tenant id parameter mechanics

Naive idea: always use tenant id, but if conjoined tenancy is disabled use the `*Default*` tenancy.
Is that feasable?

> QueueSqlCommand(). See what folks actually do now.

I use the `QueueSqlCommand` and I hope that is kept, as it's within the same transaction. Actually it's the "same transaction" thing that counts.

If outside of a session, then I just use the NpgsqlDataSource (from which I get the connection in Marten 6.x).

> Use prepared statements on everything?

I'd use that only for event related operations, not for everything by default. IIRC too much preparation can hurt too, but here I might be wrong.

**Comment by jeremydmiller** [comment]
@gfoidl The `tenant_id` column doesn't exist unless you opt into conjoined tenancy, so no, that's not feasible. And even after that, there's the possibility of `AnyTenant()` queries, so that wouldn't work even if the column was always there. It's always something:-)

I agree with you about `QueueSqlCommand()`, but the main reason we still hang the `Connection` property off of the session is either for folks using Dapper with Marten or for folks who depended on it before QueueSqlCommand() existed.

**Comment by oskardudycz** [comment]
@jeremydmiller, dumb idea, what if we add tenant id to all tables? Is the issue with tenant id, that we need to have always conditional code to add it or not?

Regarding the scope of changes, I'm definitely fine with replacing the homebrewed IRetryPolicy with Polly, especially after recent improvements and using it internally by MS.

Regarding the other changes, I'm unsure as I'd need to understand the proposal in more detail. What I can tell is that creating a new connection is costly. Not sharing it can lead to performance degradation. Other thing to add is that we should be really careful in default retry policy about that. I saw a few times when wrong settings caused ripple effect when the database was down (even not allowing it to get up because of flooding it with the open connections). Definitely we should be more explicit to our users about Pooling and test how it behaves both for Npgsql pool and PgBouncer.

I'd be happy to get rid of the CommandBuilder static methods in Weasel. Using static PostgreSQLProvider will bite us hard in the long term, so if this could help in that, I'd be more than happy.

So I'm not against the proposal, I'd need to see more details. We'd need to spend time benchmarking it. I think that it'd be good to take some inspiration from EF on how they're dealing with it. I expect that they have that optimised.

**Comment by jeremydmiller** [comment]
## Tasks on Just Batching / Positional Parameters (Jan. 8th)

- [ ] Lift `StartNewCommand()` from BatchQuery to ICommandBuilder
- [ ] Statement should call `StartNewCommand()` on apply *if* its parent is not a CTE
- [ ] Switch all methods in `CommandExtensions` to build up an NpgsqlBatch with BatchBuilder
- [ ] Create a new method in QuerySession to execute a reader from NpgsqlBatch

**Comment by jeremydmiller** [comment]
## Punchlist

- [ ] Execute benchmarks against 6.4 and the latest code. *Jeremy has a local project that's already started this work*
- [ ] Utilize Polly in all the `IConnectionLifetime` implementations. Be careful to use static lambdas in all cases
- [ ] Fine tune the Polly predicate. Utilize exponential backoff in the default
- [ ] Documentation in migration guide for connection lifecycle changes
- [ ] Documentation for customizing Polly resiliency
- [ ] New configuration for StoreOptions.CommandTimeout as an alternative to the connection string approach

**Comment by jeremydmiller** [comment]
See this draft PR: https://github.com/JasperFx/marten/pull/2918

Hasn't been rebased on master yet. Punchlist up above yet to go.

**Comment by jeremydmiller** [comment]
There are separate issues now for the docs and last couple tasks. Closing for now.
