### ISSUE TITLE
Dynamic Tenant Database Discovery

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2910]
From a JasperFx client request, we want the ability for the multi-tenancy support to be able to discover and utilize tenant databases added at runtime. This might just be a new `ITenancy` recipe. This work should include the ability to spin up an async daemon for the newly discovered tenant databases.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Make the update of tenant connection string be an upsert
- [ ] The `INodeCoordinator` strategies will need to occasionally check if there are new databases. Redesign this
- [ ] Test that a daemon can be spun up for a new database

**Comment by jeremydmiller** [comment]
This is heavily in flight in a local branch, moving on to the daemon next
