### ISSUE TITLE
Numeric "Revision" optimistic concurrency strategy

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#2961]
Today, the optimistic concurrency model uses `Guid` values as a kind of etag for document versions. That was done just to make the mechanics easy. A few folks have asked over the years for an equivalent using integer versions. Admittedly, nobody is really clamoring for this, but it would enable the [Events.FetchForWriting() story for async projections](https://github.com/JasperFx/marten/issues/2846) where the version would be the stream version.

The mechanics will be slightly different. The new update will carry the expected new version number. If that new version number is less than the existing version in the database, reject the changes.

**Comment by jeremydmiller** [comment]
## Tasks

- [x] DocumentMetadata.CurrentRevision
- [x] New `RevisionColumn` -- but it will use "version" as the same column name
- [ ] `DocumentMapping.UseNumericRevisions` -- might switch to `OptimisticConcurrencyMode.None/GuidEtag/NumericRevisions`
- [ ] `UseRevisionTracking()` on document expression FI
- [ ] Account for this in the upsert, insert, update, and override functions
- [ ] `IDocumentOperations.Store<T>(T entity, int revision)
- [ ] Fetch revision dictionaries from `VersionTracker`
- [ ] New `IRevisioned` interface that's a functional equivalent to `IVersioned` today

## Tests

- [ ] Happy path Insert() sets revision to 1
- [ ] Fetch DocumentMetadata with CurrentRevision
- [ ] Happy path Store() 
- [ ] Happy path Update()
- [ ] Happy path Store(, revision) with incremental revision
- [ ] Happy path Store(, revision) that increments more than 1
- [ ] Happy path, fetch data, update successfully
- [ ] Sad path, Store(, revision) that is rejected
- [ ] Sad path, Store() that is rejected
- [ ] Sad path, Update() that is rejected
- [ ] Override()
