### ISSUE TITLE
New asynchronous version of IConfigureMarten

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#3133]
So that it can be used with IFeatureManager from MS that requires Async signatures

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] New interface
- [ ] New activator `IHostedService`
- [ ] If using a mix of the new activator and MartenActivator, the new activator must be first!
- [ ] New fluent interface for configure marten async 
- [ ] end to end test
