### ISSUE TITLE
"Quick Append" Events

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#3138]
The normal, Marten workflow that happens in `SaveChangesAsync()` to append events captured by any permutation of `IDocumentSession.Events.Append()` is kinda heavyweight, and prone to concurrency violations if the same stream gets a lot of traffic. The pre-SaveChanges() workflow today is to:

1. Call into the database and "checkout" a number of event sequence values 
2. For every stream being started or appended to, reach out to the database and get the current version number
3. Apply all the metadata to each pending event so that all of the event metadata is available to the Inline projections (that was a big request prior to the giant V4 release)

Great, makes the projections go, but it's also a little heavyweight in terms of performance because of the extra round trips going back and forth, and it's absolutely setting *some* subset of users up for concurrency issues when they're needing to rapidly append events to the same stream. 

I'm proposing an alternative `AppendQuick()` or `StartStreamQuick()` alternative that purposely bypasses any of the current event pre-processing (and skips Inline projection usage most likely) as an explicit performance optimization. There's also the possibility of opting into this usage even for the normal Append()/StartStream() if there are no Inline projections. But I think I'd want to make that an "opt in" behavior. 

This would be an absolute prerequisite for #2533 that's been on the back log forever.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] `QuickEventAppender` --> `IEventAppender`
- [ ] `EventGraph.AppendMode` = `Rich / Quick', with `Rich` being the default
- [ ] Replace with `QuickEventAppender`
- [ ] `StreamAction.PrepareEventsFast(EventGraph graph, IMartenSession session)`
- [ ] `IEventStorage.UpdateStreamVersionFast()`
- [ ] `GeneratedStreamVersionOperationFast` --> `IStorageOperation` (pure SQL baby!)
- [ ] Clone all the append tests!!!
- [ ] Set quick append on a single session???
- [ ] Method to apply quick append on a single stream?
