### ISSUE TITLE
Database Sharding on Document Tables

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#3315]
We've talked about this over the years, but it's relevant *now* to a current JasperFx client, so moves up in priority. For only the document tables, allow users to specify table shards. This is probably mostly an effort on the Weasel side of things. Not sure how we'll go about this and what we'll allow, but this will track that work.

Ideas:

* Shard by tenant id for conjoined tenancy
* Shard on soft delete flags
* User defined shards???

**Comment by jeremydmiller** [comment]
## Tasks and Use Cases

- [ ] Quick option for LIST partitioning on soft deletes
- [ ] Quick option for partitioning on tenant id with ranges
- [ ] Quick option for partitioning on tenant id with HASH
- [ ] Partitioning on tenant id with LIST
- [ ] External managed LIST partitions
- [ ] External managed RANGE partitions
- [ ] Partitioning off of a single user selected duplicate field
- [ ] Partitioning off of multiple user selected duplicate field
- [ ] Apply the multi-tenancy partitioning for all multi-tenanted documents
