### ISSUE TITLE
Configuration flag that requires an aggregate type on StartStream()

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#3457]
Also make it throw if a stream does not already exist in Append(). Might already do that, but make sure.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] New flag on `StoreOptions.Events` for `RequireStreamType`, default is `false`
- [ ] Docs
- [ ] `StartStream` in all its overloads throws an exception if there is no stream type
- [ ] `Append` in all of its overloads will throw a `NonExistentStreamException` if the stream does not already exist
