### ISSUE TITLE
Test Suite Cleanup

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#3500]
As part of "finishing" off Marten 7 and before branching into Marten 8.0 and stealing test code for Ermine, get the tests in the best state possible. This work is heavily underway, but just want this to track the work.

## Tasks

- [x] Eliminate usage of synchronous `SaveChanges()` as much as possible
- [x] Replace one off `Exception.ShouldBeThrownBy()` usage for Shouldly equivalent
- [x] Try to replace as much of `SpecificationsExtensions` with Shouldly as possible
- [ ] Eliminate the EventSourcingTests.Utils.When class, or at least look for something better
- [ ] Merge the "quick append" tests in with the normal event capture tests as just a separate parameter (go for less code)

## CI

Make sure each test suite runs consistently in CI

- [x] CoreTests
- [x] DocumentDbTests
- [ ] EventSourcingTests
- [ ] ValueTypeTests
- [ ] LinqTests
- [ ] PatchingTests (think this one is fine)
- [ ] Noda Time tests
- [ ] AspNetCore tests
- [ ] PLv8 tests
- [ ] MultiTenancyTests
- [ ] CommandLineTests

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/marten/pull/3502
