### ISSUE TITLE
Convert to JasperFx in Marten 8

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#3519]
Placeholder for the work to utilize the new JasperFx helper. Really keeping notes for now.

## Tasks

- [ ] Make the existing codegen related APIs and application assembly stuff all be [Obsolete]
- [ ] Utilize defaults from JasperFx for CodeGeneration & AutoCreate

## Retire these APIs?

- [ ] Mark all code gen related items on StoreOptions as [Obsolete]? 
- [ ] Delete the optimized workflow

**Comment by jeremydmiller** [comment]
Done locally.

**Comment by jeremydmiller** [comment]
I think this is cancelled for now.
