### ISSUE TITLE
Ability to stream json data directly to another stream

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#585]
For the case where all you want to do is get some results from the server as JSON and send it down to an HTTP response. Skip the JSON string altogether and just copy bytes from one stream to another.

**Comment by jeremydmiller** [comment]
Think this is going to have to be in 2.0

**Comment by jeffdoolittle** [comment]
Curious if GraphQL is still in the works as mentioned here: https://jeremydmiller.com/2018/06/07/planning-the-next-couple-marten-releases/ 

Note that this blog post references #585

**Comment by Miggleness** [comment]
Has there been any thought on the API to get the streaming option?  Like `.Streaming()` at the end of a query?

There would still be a need to convert stream to UTF8 since `jsonb` isn't stored in that encoding.

**Comment by jeremydmiller** [comment]
@Miggleness The serializer shouldn't have to get involved at all. It should be Npgsql's streaming support effectively pushing bytes directly to the HttpResponse.Body. There's gonna be some hiccups maybe if we need to strip out some serializer specific noise, but we'll have to cross that bridge when we get to it

**Comment by Miggleness** [comment]
I'll find time to play around with it

**Comment by jeremydmiller** [comment]
## Tasks

I'm not gonna bother with `Single()` or `SingleOrDefault()` mechanics right now.

- [ ] `IQuerySession.Json.TryStream<T>(string, id) : Task<bool>`
- [ ] `IQuerySession.Json.TryStream<T>(int, id) : Task<bool>`
- [ ] `IQuerySession.Json.TryStream<T>(Guid, id) : Task<bool>`
- [ ] `IQuerySession.Json.TryStream<T>(long, id) : Task<bool>`
- [ ] `IQuerySession.Json.TryStreamMany<T>(string, id[]) : Task`
- [ ] `IQuerySession.Json.TryStreamMany<T>(int, id[]) : Task`
- [ ] `IQuerySession.Json.TryStreamMany<T>(Guid, id[]) : Task`
- [ ] `IQuerySession.Json.TryStreamMany<T>(long, id[]) : Task`
- [ ] `IMartenQueryable<T>.StreamMany(stream, token) : Task`
- [ ] `IMartenQueryable<T>.StreamOne(stream, token) : Task<bool>` -- returns null if none is found.
