### ISSUE TITLE
Undelete and permanently delete soft deleted documents

### ISSUE THREAD

**Issue by ejsmith** [JasperFx/marten#826]
I see that you can query for deleted documents, but I don't see any way to either permanently delete them or undelete them. Is that currently possible?

**Comment by jeremydmiller** [comment]
Through straight sql, but nothing built in. That wouldn't be a big change. I wouldn't block 2.0 on that though

**Comment by ejsmith** [comment]
Yeah, definitely not a blocking issue. Just something I ran into and was wondering about. Add this to the list of things I will try and find time to submit a PR for. 😄

**Comment by jeremydmiller** [comment]
This one might not be that bad. 

I think I'd add to `IDocumentSession`:

```
// Annoying, but there are four overloads
void HardDelete<T>(id);
void HardDelete<T>(T document);
void HardDeleteWhere<T>(Expression<Func<T, bool>>)
```

In both cases, look at the `DocumentSessionBase` code for `Delete() / DeleteWhere()` and how it delegates to `DocumentStorage<T>`. You might wanna make a `HardDeletion : Deletion` type that takes in a that use a `HardDelete` object as its operation.


I'd just add new corresponding methods in `DocumentStorage<T>` to force the usage of the new `HardDeletion` statement. 

I promise that will all look more clear after reading through the code;-)

**Comment by jeremydmiller** [comment]
For reversing the deletion on a soft delete, I think you make a new `IOperationFragment` like `SoftDelete`, but reverse it to update the deleted flag to false. The problem here is that the default filtering maybe be trying to filter out deleted items automatically. That might be a touch trickier

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] `UnSoftDelete` implements `IOperationFragment`
- [ ] `IDocumentSession.HardDelete<T>(T document)`
- [ ]  `IDocumentSession.HardDelete<T>(string tenantId, T document)`
- [ ] `IDocumentSession.HardDeleteWhere<T>(Expression<Func<T, bool>>)
- [ ] `IDocumentSession.HardDelete(id)` for Guid, int, long, string
- [ ] `IDocumentSession.HardDeleteByTenant(tenantId, id)` for Guid, int, long, string
