### ISSUE TITLE
Opt into "revisioned" documents

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#846]
We've had a request to support using integers for the document versions instead of Guid's. And since  I don't care to break all the existing databases, we're making this configurable. See #835 for some context.

## Acceptance Tests
- [ ] Insert doc w/ int versions
- [ ] Update doc w/ int versions happy path
- [ ] Update doc w/ int versions concurrency violation
- [ ] Upsert doc w/ int versions happy path
- [ ] Upsert doc /w int versions concurrency violation
- [ ] IDocumentSession.Store(int, doc) scenario, happy and sad path
- [ ] Patching API w/ a doc w/ int versions
- [ ] Bulk inserts w/ a doc w/ int versions
- [ ] Hierarchical documents w/ int revisions
- [ ] DocumentMetadata w/ int revisions
- [ ] DocumentTransforms w/ int revisions

## Tasks

- [ ] `[Version]` attribute for denoting the version property or field
- [ ] `Version(x => x.Version)` syntax in the FI
- [ ] `DocumentMapping.VersionField`
- [ ] Alternate `DocumentTable` construction
- [ ] Alternate Upsert/Insert/Update/Overwrite functions
- [ ] VersionTracker - need it to expose int's in addition to Guid's. 
- [ ] `Resolver` -- have the sproc writer take in teh VersionTracker. Go farther, all lambda generation needs to take in the VersionTracker instead of the versions
- [ ] `Resolver` needs to have a means to set versions on docs?
- [ ] If a version property exists, have it written to the object before an update, and have it rolled back if the update fails, or maybe have the sproc's set the version on success? Do it in OptimisticConcurrencyCheck. Have it also take in Action<T, int> or Action<T, Guid> to handle the setting?
- [ ] Need an int version of OptimisticConcurrencyCallback, or maybe make it be a generic?

**Comment by jeremydmiller** [comment]
And this is just too damn big. Shutting this down.
